---
name: TopBlock
api: 3.0.0
author: Kygekraqmak
version: 1.0.0
main: Kygekraqmak\TopBlock\TopBlock

commands:
    topblock:
        description: TopBlock server StayWait
        permission: topblock.cmd
        usage: "/topblock [player]"

permissions:
    topblock.cmd:
        description: Izin untuk menggunakan command /topblock
        default: true
...
